config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :availabilities
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "sessions#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :require_login

  def show
  end
  
  before_action :set_availability, only: [:show, :edit, :update, :destroy]

  # GET /availabilities
  # GET /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1
  # GET /availabilities/1.json
  def show
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
  end

  # GET /availabilities/1/edit
  def edit
  end

  # POST /availabilities
  # POST /availabilities.json
  def create
    @availability = Availability.new(availability_params)

    respond_to do |format|
      if @availability.save
        format.html { redirect_to @availability, notice: 'Availability was successfully created.' }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1
  # PATCH/PUT /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to @availability, notice: 'Availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1
  # DELETE /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: 'Availability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def availability_params
      params.require(:availability).permit(:employee_id, :starttime, :endtime)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
before_action :require_login

  def show
  end
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.where(["firstname LIKE ?", "%#{params[:search]}%"])
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:firstname, :lastname, :email, :address, :country, :city, :postalcode, :password, :phonenumber)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:username, :password)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < Clearance::PasswordsController
  def deliver_email(user)
    ClearanceMailer.delay.change_password(user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/availabilities/_form.html.erb
<header>
  <div id="banner">
    <div id="banner-content">
      <div id="logo">
        <%= image_tag "logo.png", size: "100x100" %>    
      </div>
    </div>
  </div>
</header>
<h1>Enter information</h1>
  <%= form_with(model: availability, local: true) do |form| %>
  <% if availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
      <% availability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div align="center">
  <div class="field">
    <%= form.label :name, 'Enter your ID' %>
    <%= form.text_field :employee_id, id: :availability_employee_id %>
  </div>

  <div class="field">
    <%= form.label :name, 'Configure Start Time' %>
    <%= form.datetime_select :starttime, id: :availability_starttime %>
  </div>

  <div class="field">
    <%= form.label :name, 'Configure End Time' %>
    <%= form.datetime_select :endtime, id: :availability_endtime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/availabilities/edit.html.erb
<h1>Editing Availability</h1>

<%= render 'form', availability: @availability %>

<%= link_to 'Show', @availability %> |
<%= link_to 'Back', availabilities_path %>

app/views/availabilities/index.html.erb
<header>
  <div id="banner">
    <div id="banner-content">
      <div id="logo">
        <%= image_tag "logo.png", size: "100x100" %>    
        <div id="signed_in">
          <% if signed_in? %>
            <div style="color: white; font-size: 17px; margin-bottom: 10px;" >
                You are signed in as: <%= current_user.email %>
              </div>
              <div style="text-align: right;">
                <%= button_to 'Sign out', sign_out_path, method: :delete %>
              </div>
          <% else %>
              <%= link_to 'Sign in', sign_in_path %>
          <% end %>   
       </div>
      </div>
    </div>
  </div>
</header>

<p id="notice"><%= notice %></p>

<h1>Availabilities</h1>

<table align="center">
  <thead>
    <tr>
      <th class="rows">Employee</th>
      <th class="rows">Start time</th>
      <th class="rows">End time</th>
      <th colspan="3" class="rows">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td class="rows"><%= link_to availability.employee.firstname + " " + availability.employee.lastname, availability.employee %></td>
        <td class="rows"><%= availability.starttime %></td>
        <td class="rows"><%= availability.endtime %></td>
        <td class="rows"><%= link_to 'View', availability %></td>
        <td class="rows"><%= link_to 'Edit', edit_availability_path(availability) %></td>
        <td class="rows"><%= link_to 'Delete', availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="newavailability">
  <%= link_to 'New Availability', new_availability_path, :style=>'color: white;' %>
</div>

<div id="employeebutton">
  <%= link_to 'Return', employees_path, :style=>'color: white;' %>
</div>

app/views/availabilities/new.html.erb
<div align="center">
<%= render 'form', availability: @availability %>
</div>
<div id="back"> 
	<%= link_to 'Back', availabilities_path, :style => 'color: white;' %>
</div>

app/views/availabilities/show.html.erb
<header style="padding-top: 8em;">
  <div id="banner">
    <div id="banner-content">
      <div id="logo">
        <%= image_tag "logo.png", size: "100x100" %>    
      </div>
    </div>
  </div>
</header>

<p id="notice" align="center"><%= notice %></p>

<table align="center">
	<thead>
		<tr>
			<td>
				<p>
				  <strong>Employee:</strong>
				<td><%= link_to @availability.employee.firstname + " " + @availability.employee.lastname, @availability.employee %>
				</td>
				</p>
			</td>
		</tr>
		<tr>
			<td>
				<p>
	  				<strong>Starttime:</strong>
	  				<td><%= @availability.starttime %></td>
				</p>
			</td>
		</tr>
		<tr>
			<td>
				<p>
	  				<strong>Endtime:</strong>
	 			 	<td><%= @availability.endtime %></td>
				</p>
			</td>
		</tr>
	</thead>
</table>
<div id="edit_back">
	<%= link_to 'Edit', edit_availability_path(@availability), :style => 'color: white;' %> |
	<%= link_to 'Back', availabilities_path, :style => 'color: white;' %>
</div>

app/views/employees/_form.html.erb
<header style="padding-top: 2em;">
  <div id="banner">
    <div id="banner-content">
      <div id="logo">
        <%= image_tag "logo.png", size: "100x100" %>    
      </div>
    </div>
  </div>
</header>
<h1>Enter information</h1>
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>
      <div class="container" style="padding-top: 30px">
        <form>
          <div class="form-horizontal">
            <div class="form-group">
              <div class="field">
                <%= form.label :name, 'First name' %>

                  <%= form.text_field :firstname, id: :employee_firstname, :class => 'form-control' %>

              </div>
            </div>
            <div class="form-group">
              <div class="field">
                <%= form.label :name, 'Last name' %>

                  <%= form.text_field :lastname, id: :employee_lastname, :class => 'form-control' %>

              </div>
            </div>
            <div class="form-group">
              <div class="field">
                <%= form.label :email %>
                  <%= form.text_field :email, id: :employee_email, :class => 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <div class="field">
                <%= form.label :address %>

                  <%= form.text_field :address, id: :employee_address, :class => 'form-control' %>

              </div>
            </div>
            <div class="form-group">
              <div class="field">
                <%= form.label :country %>

                  <%= form.text_field :country, id: :employee_country, :class => 'form-control' %>

              </div>
            </div>
            <div class="form-group">
              <div class="field">
                <%= form.label :city %>

                  <%= form.text_field :city, id: :employee_city, :class => 'form-control' %>

              </div>
            </div>
            <div class="form-group">
              <div class="field">
                <%= form.label :name, 'Postal Code' %>

                  <%= form.text_field :postalcode, id: :employee_postalcode, :class => 'form-control' %>

              </div>
            </div>
            <div class="form-group">
              <div class="field">
                <%= form.label :name, 'Phone Number' %>

                  <%= form.text_field :phonenumber, id: :employee_phonenumber, :class => 'form-control' %>

              </div>
            </div>
            <div class="actions" id="createemployee">
              <%= form.submit %>
            </div>
          </div>
        </form>
      </div>
    <% end %>

app/views/employees/edit.html.erb
<%= render 'form', employee: @employee %>
<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<div id="banner">
  <div id="banner-content">
    <div id="logo">
      <%= image_tag "logo.png", size: "100x100" %>    
      <div id="signed_in">
          <% if signed_in? %>
            <div style="color: white; font-size: 17px; margin-bottom: 10px;" >
                You are signed in as: <%= current_user.email %>
              </div>
              <div style="text-align: right;">
                <%= button_to 'Sign out', sign_out_path, method: :delete %>
              </div>
          <% else %>
              <%= link_to 'Sign in', sign_in_path %>
          <% end %>   
       </div>
    </div>
  </div>
</div>
<h1>Employees</h1>

<div id="search">
<%= form_tag employees_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>
</div>

<table align="center" id="employeetable">
  <thead>
    <tr>
      <th class="rows">First Name</th>
      <th class="rows">Last Name</th>
      <th class="rows">Email</th>
      <th class="rows">Address</th>
      <th class="rows">Country</th>
      <th class="rows">City</th>
      <th class="rows">Postal Code</th>
      <th class="rows">Phone Number</th>
      <th colspan="3" class="rows">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td class="rows"><%= employee.firstname %></td>
        <td class="rows"><%= employee.lastname %></td>
        <td class="rows"><%= employee.email %></td>
        <td class="rows"><%= employee.address %></td>
        <td class="rows"><%= employee.country %></td>
        <td class="rows"><%= employee.city %></td>
        <td class="rows"><%= employee.postalcode %></td>
        <td class="rows"><%= employee.phonenumber %></td>
        <td class="rows"><%= link_to 'View', employee %></td>
        <td class="rows"><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td class="rows"><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="newemployee">
  <%= link_to 'New Employee', new_employee_path, :style=>'color: white;' %>
</div>

<div id="availabilitybutton">
  <%= link_to 'Availability', availabilities_path, :style=>'color: white;' %>
</div>

app/views/employees/new.html.erb
<div style="text-align: left;">
	<%= render 'form', employee: @employee %>
</div>
<div align="center">
	<%= link_to 'Back', employees_path %>
</div>

app/views/employees/show.html.erb
<header>
  <div id="banner">
    <div id="banner-content">
      <div id="logo">
        <%= image_tag "logo.png", size: "100x100" %>    
      </div>
    </div>
  </div>
</header>
<h1>Your information</h1>
<table align="center">
  <thead>
    <tr class="rows">
      <p id="notice" align="center"><%= notice %></p>
    </tr>
    <tr class="rows">
      <th>
        <p>
          <strong>First Name:</strong>
        </p>
        <td><strong><%= @employee.firstname %></strong></td>
      </th>
    </tr>
    <tr class="rows">
      <th>
        <p>
          <strong>Last Name:</strong>
        </p>
        <td><strong><%= @employee.lastname %></strong></td>
      </th>
    </tr>
    <tr class="rows">
      <th>
        <p>
          <strong>Email:</strong>
        </p>
        <td><strong><%= @employee.email %></strong></td>
      </th>
    </tr>
    <tr class="rows">
      <th>
        <p>
          <strong>Address:</strong>
        </p>
        <td><strong><%= @employee.address %></strong></td>
      </th>
    </tr>
    <tr class="rows">
      <th>
        <p>
          <strong>Country:</strong>
        </p>
        <td><strong><%= @employee.country %></strong></td>
      </th>
    </tr>
    <tr class="rows">
      <th>
        <p>
          <strong>City:</strong>
        </p>
        <td><strong><%= @employee.city %></strong></td>
      </th>
    </tr>
    <tr class="rows">
      <th>
        <p>
          <strong>Postal Code:</strong>
        </p>
        <td><strong><%= @employee.postalcode %></strong></td>
      </th>
    </tr>
    <tr class="rows">
      <th>
        <p>
          <strong>Phone Number:</strong>
        </p>
        <td><strong><%= @employee.phonenumber %></strong></td>
      </th>
    </tr>
</table>
<div id="edit_back">
  <%= link_to 'Edit', edit_employee_path(@employee), :style => 'color: white;' %> |
  <%= link_to 'Back', employees_path, :style => 'color: white;' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jake's Café</title>
    <%= favicon_link_tag 'logo.png' %>
    <%= csrf_meta_tags %>
<<<<<<< HEAD

    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
=======
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
>>>>>>> 5c912a309521844578ef0952e478d4fc962a4a62
  </head>
<div id="banner">
  <div id="banner-content">
    <div id="logo">
      <%= image_tag "logo.png", size: "100x100" %>    
  </div>
</div>
  <body>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/logins/_form.html.erb
<%= form_with(model: login, local: true) do |form| %>
  <% if login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :login_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :login_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/x-icon" href="favicon.png">
  <script src="script.js" type="text/javascript"></script>
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

    <title>Login</title>
  </head>

  <body style="min-height: 700px;">

    <div id="banner">
      <div id="banner-content">
        <div id="logo">
          <%= image_tag "logo.png", size: "100x100" %>    
        </div>
      </div>
    </div>

    <div class="container">
      <div class="jumbotron" id="jumbotronLogin">
          <h1 id="login">Login</h1>
        <div class="form-group" id="div_usr">
          <label for="usr">Username</label>
          <input type="text" class="form-control" id="usr">
        </div></br>
        <div class="form-group" id="div_pwd">
          <label for="pwd">Password</label>
          <input type="password" class="form-control" id="pwd">
        </div>
        <div id="signIn_button"></br>
          <button type="button" class="btn btn-xl" id="button">Sign In</button>
        </div>
      </div>
      <div class="url" style="margin-bottom: 1.5em;">
        <%= link_to 'Create an account', new_login_path %>
      </div>
        <a href="forgotPassword.html" class="url">Forgot your password?</a> 
      </div>     
    </div>
  </body>
</html>

app/views/logins/new.html.erb
<head>
	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
</head>

<body style="min-height: 700px;">
	<div id="banner">
	  <div id="banner-content">
	    <div id="logo">
	      <%= image_tag "logo.png", size: "100x100" %>    
	    </div>
	  </div>
	</div>


<div class="container" align="center">
	<div class="jumbotron" id="jumbotronLogin">
		<h1 style="font-size: 35px; font-family: Lato, sans-serif; ">Create your Account!</h1>
		<div style="padding-top: 3em; padding-bottom: 3em;">
			<div style="font-size: 15px;">
				<%= render 'form', login: @login %>
				<%= link_to 'Back', logins_path %>
			</div>
		</div>
	</div>
</div>
</body>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @login.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login.password %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/users/_form.html.erb
<div align="center">
	<div class="text-field">
	  <%= form.label :email %>
	  <%= form.text_field :email, type: 'email' %>
	</div>

	<div class="password-field">
	  <%= form.label :password %>
	  <%= form.password_field :password %>
	</div>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>